INSERT INTO Sklady (Mesto, Kapacita) Values ('Hradec Kralove','Velky');
insert into Sklady (Mesto, Kapacita) values ('Tanashichō', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Montauban', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lasi Dua', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Burgeo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ueki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ryazanskaya', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Oslo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Weifang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Malanje', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bến Cầu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('San Fernando', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dārchulā', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Meylan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hepingjie', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vatutine', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Barcelona', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nggambel', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nansha', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Frutillar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cabouco', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Carrasqueira', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Parreira', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Palkovice', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Carmo do Paranaíba', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Huanchaco', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lanot', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tonjongsari', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gisiliba', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Polykárpi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cimonyong', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sida', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Balangpule', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chengji', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sumberkindagan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Miaojie', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Duluth', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xiagang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Inuvik', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Martanesh', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dampek', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Medellín', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Qal‘ah-ye Kuhnah', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Port-Vila', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dajt', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hūn', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yishan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Raojān', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Niono', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Feitoria', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Emnambithi-Ladysmith', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Krasnosilka', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vale', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Frösön', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sydney', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Montpellier', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Quintãs', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lipnica Wielka', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('San José', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Remedios', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Muyi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('General Manuel J. Campos', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cikiruh', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xuedian', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Rizómata', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Little Rock', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('San Jose', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ikhtiman', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Stockholm', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Guisser', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pivka', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bousso', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Puricay', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hongxingqiao', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xiaohebian', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jihuluntu Sumu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Antonio Toledo Corro', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santa Luzia', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chernyanka', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Salerno', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shiqian', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Punta de Bombón', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lávara', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pliwetan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tây Hồ', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Komi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lieksa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sangzhen', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Yantai', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Saint Lucia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Manalu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ranot', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('El Cortezo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Castelsarrasin', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Hollola', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Turenki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Phitsanulok', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Markala', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tripoli', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Margotuhu Kidul', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mogzon', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Longqiao', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Novyy Svit', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Huangbizhuang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chacabuco', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sangat', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Limbe', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bordeaux', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Malamig', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Anaco', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Haarlem', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Szombathely', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Linjiang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bureng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Boje', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tanahmerah', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Antigonish', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kill', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cikembang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dawu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kuala Lumpur', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Muqi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Vurğun', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Milano', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Caringin Lor', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('P’yŏngsŏng', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ea T’ling', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('San Cristóbal Totonicapán', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lijia', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Shancheng', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Quarteira', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Baratan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Verkhnyaya Tura', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Talnakh', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Maonon', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tornio', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Middleton', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mito-shi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jiudian', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xiangshui', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Smederevska Palanka', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('San Nicolas', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Saguing', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Vänersborg', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Norfolk', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dazhigu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kitahiroshima', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nykvarn', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nunbaundelha', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yasnyy', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gornyy', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hässleholm', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tsuruoka', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yimnón', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vilar do Monte', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Okpoga', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wonosari', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nałęczów', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Heku', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dzhubga', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tambalisa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Frederico Westphalen', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Corgo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dasha', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Mikhaylovsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Konso', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Peliyagoda', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Minna', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Metahāra', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Marseille', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bagiktinggang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ozurgeti', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Panevėžys', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tanalt', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Stalowa Wola', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sanmiaoqian', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ecilda Paullier', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Saint Lucia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hitura', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dobratice', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ekasapta', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Wyśmierzyce', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Siaya', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Chom Bueng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Perivóli', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gourma Rharous', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zheleznogorsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sydney', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hat Yai', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Lishui', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Makato', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Iqaluit', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xujiahe', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santa Eulalia', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zomba', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Alicante/Alacant', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gurbuki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tsiroanomandidy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pavlovskaya', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Madīnat Ḩamad', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tangnan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Vondrozo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Goght’', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Plaeng Yao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sulmierzyce', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('San Miguel', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Luena', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zhaogezhuang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jianqiao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('San Pedro', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yeliguan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kiiminki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ngeru', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Punsu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sanguinheira', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chongqing', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hengdian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zhoutian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Paprotnia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Poretskoye', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Liuqu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Giraldo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Itu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Parachinar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gustavsberg', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Doksy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Castro Daire', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gagarin', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Belawang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bang Bon', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tours', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dolní Kounice', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Charxin', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chachoengsao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Beira', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Qaraçuxur', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pithári', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Anaco', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chulakivka', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shangyong', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Daxindian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kanigorokrajan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kwaluseni', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lübeck', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Alcáçovas', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santa Rosa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ube', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jose Maria Morelos', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nijmegen', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Khust', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chian Yai', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tahala', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xiaojie', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('San Pedro One', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Al Buq‘ah', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Timon', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sabtang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Francisco Beltrão', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Liuji', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Puzi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Revelstoke', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Aksarka', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sumurwaru', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('El Quetzal', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('La Virtud', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tawa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nangabere', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sukhinichi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('El Doncello', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Irapa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ouro Preto', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dallas', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Takengon', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ilha de Moçambique', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Balzar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Vinež', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Saumur', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Baijiang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santa Fe de la Vera Cruz', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Babat', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nijiangping', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Aykol', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mosteiro', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Antonina', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sîr ed Danniyé', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Psychikó', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chacarita', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Řehlovice', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Omurtag', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jackson', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ar Rudayyif', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lufang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pragen Selatan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chusovoy', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kiarajangkung', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('San Francisco', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Le Mans', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kuala Bintang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jovellar', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Alor Star', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Zala', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('São Félix do Xingu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mandaguari', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Molodohvardiys’k', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ruokolahti', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zepita', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zhenzhushan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tabunok', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Vila de Sal Rei', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Warungbanten', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lago dos Rodrigues', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chłapowo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sirghāyā', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Lubowidz', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jianshe', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mhamid', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('London', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Juan Adrián', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Khānaqāh', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Daxing', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('San Roque', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shaoha', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nesebar', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gaojia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jiandou', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shenshu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dan Makham Tia', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zhenhai', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dayr al Ghuşūn', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Täby', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dayangzhou', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nesebar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cisek', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tsaghveri', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Zhongba', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('La Foa', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Białogard', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Huangzhan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tha Mai', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Juhaynah', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tawun', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pancol', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bergen', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Pacora', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bayanbulag', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Konice', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Daxi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mompós', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Valença', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shirgjan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Heshan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yangdang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sasykoli', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kizlyar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Khirdalan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Moravský Písek', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Port-Vila', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Västra Frölunda', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sankt Andrä-Höch', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Washington', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Duqiao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Longhe', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sirnarasa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Machagai', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('El Charco', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Svilajnac', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mūsa Khel Bāzār', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nong Ki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sabinópolis', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gangmei', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Béoumi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dārayyā', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Duiwelskloof', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Goúrnes', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yanqi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Londrina', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Racine', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Salt Lake City', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jiyizhuang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Niamtougou', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tegalgede Kulon', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dali', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Wa’eryi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lhokkruet', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Turpo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shancheng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Valledupar', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Grand Forks', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Medvedok', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Longtou’an', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ngantru', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Futian', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Stapleford', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Wanzhi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Lao Suea Kok', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Biharamulo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kyankwanzi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kuzhu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Karanganyarkrajan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Eksjö', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Cimo de Vila', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Leninogorsk', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('As Saffānīyah', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Velikiy Novgorod', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Rauna', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Youdian', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sirnasari', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Inčukalns', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Qinhong', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Krasnoarmeysk', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yiqi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shah Alam', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Rongelap', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kawanoechō', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sámara', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Iwamizawa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Puerto de Nutrias', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gongming', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dongtou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Morocelí', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Brooklyn', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Mingguang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Puerto Berrío', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Huitán', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bowen Island', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sekolan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Wanurian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Rossosh’', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Fuji', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xishan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Veřovice', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yläne', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mikulintsy', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Pantenan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jiehu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bắc Ninh', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shibli', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Independencia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Benjamin Constant', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gayam', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shido', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wanjia', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Simpang Ulim', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sasebo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Korisós', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kario', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dassun', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Changtang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lemenhe', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bungur', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Conde', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Lacdayan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pasar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jilma', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Poli', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gorno-Altaysk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Marquard', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Idrinskoye', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cijambe', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ningxin', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vargas', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shuikou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Riachão do Jacuípe', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Karangwaru', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Apopa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Wolomarang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Coutances', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Caratinga', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('La Estancia', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Hecheng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Yelabuga', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xijiang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mondokan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Carregueira', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Banqiao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Correia Pinto', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pining', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lamduan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jurangjero', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Anguil', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mataloko', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shangtang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sukth', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kiambu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mont-Royal', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shagang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Hägersten', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Potikosin', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Hengxi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Cibitung', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gościeradów', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ijūin', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('La Rochelle', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bagikkedok Lauk', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sidaurip', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Leran Wetan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Burla', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kilafors', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Wola Jachowa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sidomulyo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vlycháda', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Aroa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Konstantinovo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Torres Novas', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Rothesay Bay', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kertasari', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Houjia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Villa María', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xianning', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Cipolletti', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tabu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jixing', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kamsack', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Oja', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xikou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Gangshangji', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Usogorsk', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jinshanwei', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Aurora', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Évodoula', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Padangguci', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Matangshan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Santa Cecília', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dobczyce', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tungipāra', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Atikokan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jiangcun', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Esteio', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Boleiros', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kudang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Itaocara', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Saihan Tal', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Amper', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zdolbuniv', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Simenqian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ngantru', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jurm', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Brejieira', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Erhaodi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Khadīr', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shanjiao', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Cartago', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shevchenkove', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Malainen Luma', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tatsuno', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bouctouche', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lahoysk', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Štitar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Skópelos', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Balakliya', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zaječov', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sandaoba', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vondrozo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Platičevo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Elverum', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Robonkon', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jixiang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yambrasbamba', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kelin', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wangmang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dzerzhinsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yongning', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Morfovoúni', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kefar Shemaryahu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Eloúnda', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Portela', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Asbestos', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Hyrynsalmi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Riachão das Neves', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bayart Huxu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gaoming', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Loay', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Pampanito', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Senggreng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Chapayevka', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tete', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Siqian', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Az Zawr', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Baoxu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('São Martinho', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bacong', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Toungo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Evxinoúpolis', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tvŭrditsa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Alangalang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tiouli', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yangping', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mont-Royal', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Daliuhao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nicosia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ampara', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sumberjo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Qobu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Haoxue', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Mēga', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ekerö', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Santo Antônio da Platina', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Santa Maria', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Oroquieta', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Libu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sariwŏn', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('San Miguel', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Varėna', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jinsha', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Qabaqçöl', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Salawu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gorzyczki', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Littleton', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Indramayu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Mihara', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Fangtian', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dante Delgado', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Korba', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lüjiabao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Banamba', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Saint-Pierre', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ximafang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kil', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santo Tomas', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vitória da Conquista', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Féres', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gabi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Benzilan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Káto Glikóvrisi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dikhil', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jasień', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gaohe', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Miedzichowo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Évry', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zhukovskiy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tianbao', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Balung Barat', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Frolovo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Junxi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Jingyang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Beranci', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xiaoling', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xiangfu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Novyye Cherëmushki', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zengjia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pęczniew', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Praia da Tocha', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pantai', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Liuzhi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jadowniki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Puzi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vyshneye Dolgoye', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xinrong', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Konice', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bai’e', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bang Saphan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chunjiang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bombarral', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kavásilas', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Huangjiabu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sumberdangdang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mytishchi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Angoram', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Estreito Câmara de Lobos', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Feyẕābād', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Īz̄eh', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Charlotte', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Castlebellingham', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gąsocin', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cihurip Satu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pemzashen', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Saiki', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Adassil', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vodnyy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Beaufort', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sölvesborg', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Yangxunqiao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Aminga', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Onzaga', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Taiyu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Busungbiu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Uyovu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Angochi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Shangcunba', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Cangshan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zhugang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chipinge', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Karangbungur', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('La Gloria', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pasar Kulon', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Querocotillo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Barreiros', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yumaguzino', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tangcun', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Aozai', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Shiyun', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kalahang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Potongan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kuče', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nice', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Utarapasar', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Umm as Summāq', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Velké Hoštice', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tartaro', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bihoro', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Matou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bous', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Carabamba', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kopychyntsi', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ajaccio', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Iida', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kole', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Changliang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Osypenko', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ryazanskaya', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xiaozhoushan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Waterloo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Chefchaouene', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xiongjia', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Masallātah', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Quiches', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ballitoville', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Meijiahe', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jeffrey’s Bay', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Luleå', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mekkaw', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tupã', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chouto', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Žleby', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Liancheng', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Timmins', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Didi Lilo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Carquefou', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Asino', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kadugannawa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Fresno', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Chandal Bā’ī', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chlumec nad Cidlinou', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wakefield', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Seiça', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Daejeon', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lunsar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Anta', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('El Refugio', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Szczawnica', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('20 de Noviembre', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Pompano Beach', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kuçovë', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Motygino', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sumberpandan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vendas de Galizes', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Saitama', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Radostowice', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kiamba', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pananaw', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Borlänge', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Salaverry', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jiujiang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Loznitsa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Höfn', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ciduren', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ilām', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sidoaji', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yasnyy', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dayuan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Peukanbada', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wajak', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('La Unión', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kugri', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Vårgårda', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Göteborg', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zaniemyśl', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dzwola', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xankandi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Paraiso', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Guandi', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cawayan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dijon', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dushang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Paris 15', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kuusjoki', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bangkok', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Shīrvān', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Xianghua', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dorotea', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kangping', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kabarnet', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Popovo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Fenshui', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nūrābād', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Leonídio', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nama', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Lunéville', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Przytyk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Texíguat', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Zator', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Empório', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Arroteia', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Cambanay', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Mikhaylov', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Luanda', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Granada', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Batur Kidul', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xianju', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Rothesay Bay', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Puji', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Liancheng', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Łazy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nong Chik', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Fuxi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('La Cruz', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yanjiang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tambakan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Curuzú Cuatiá', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Votkinsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Rogoza', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Andalan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bangunsari', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Thị Trấn Nguyên Bình', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wanquan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Zigong', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Boulaouane', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Jincun', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dijon', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kuala Terengganu', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mercedes', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Nokaneng', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yangkang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Huage', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ramat Gan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Karengan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kurashiki', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gent', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Songgai', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Alaverdi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Omīdcheh', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Herrera', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Leleque', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Gwangtan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Shinan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Hamilton', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Laveiras', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Shancheng', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pingtang', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Cerklje na Gorenjskem', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santo Tomas', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Shijing', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Żabieniec', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nioki', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lenchwe Le Tau', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Granja', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Milwaukee', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Benešov nad Ploučnicí', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Ballitoville', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tulsa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('São Silvestre', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Debrecen', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Düsseldorf', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Singajaya', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kyzyldzhar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kujama', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dulian', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Isla', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Eséka', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Boafeo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Vila Franca das Naves', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Durrës', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Bielawa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pajo', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Mbanza-Ngungu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Fabianki', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bucheon-si', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Rongcheng', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Lazarevac', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tonekābon', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cruzeiro', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Yangp''yŏng', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Watrous', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Girón', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Marinići', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Budziszewice', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Emiliano Zapata', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Trinaterra', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Zhenzhushan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Örebro', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Xiacang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nogueira', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Santo Domingo Este', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Youchou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Chimbas', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Momil', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Al Balyanā', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Město Albrechtice', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Midrand', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sobreira', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sosnovoborsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Hallstahammar', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Falun', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Rogoza', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Zhifudao', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Quintã', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lawa-an', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Miān Channūn', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xindu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Korolëv Stan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Calubcub Dos', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Göteborg', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Khān Arnabah', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Yeliguan', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tsybli', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Hollywood', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Namballe', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sironko', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Satuek', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Bagumbayan', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Turnišče', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Neuquén', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Duobagou', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bureya', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Richmond', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dolní Rychnov', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Labège', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Garies', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Abobo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Marseille', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('La Quiaca', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Dabou', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ballsh', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Samburat', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Samdrup Jongkhar', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Salcedo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Minglanilla', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Pravdinsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sanhe', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Cần Giờ', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Paucarbamba', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Huainan', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ar Rumaythīyah', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Bisert’', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dengjia', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Anse Boileau', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dadus', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Osekovo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Nanyang', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Paprotnia', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('João Pessoa', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sassandra', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Sicaya', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sann', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Castleknock', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Xitou', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kon Tum', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Ko Samui', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Sioux City', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Richmond', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kolumbug', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Fernandópolis', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tingsiqiao', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lingqian', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Jianli', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('El Aïoun', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Valle de Guanape', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kotikawatta', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Socota', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tierra y Libertad', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Killorglin', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Ponggok', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Chunhua', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Wiang Chiang Rung', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Laweueng', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Tianzhuang', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Leganes', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Rostokino', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Podwilk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Dzhubga', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Tonshayevo', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Irricana', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Nakamura', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('San Pedro', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('La Courneuve', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Leninsk', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Enköping', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Santiago Nonualco', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pskov', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Isheyevka', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Oslo', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Pedro II', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Dian-ay', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Alvaiázere', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kamień Pomorski', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Qingban', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kota Bharu', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Purwodadi', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Mooka', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Qārah', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Capissayan Sur', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Gourcy', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Sesheke', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Paris La Défense', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Porsgrunn', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Kalangala', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Tabonoc', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Palmeiros', 'Velky');
insert into Sklady (Mesto, Kapacita) values ('Kurungannyawa', 'Maly');
insert into Sklady (Mesto, Kapacita) values ('Kota Kinabalu', 'Stredni');
insert into Sklady (Mesto, Kapacita) values ('Lens', 'Maly');
