INSERT INTO Zbozi (Cena,Nazev) VALUES (14211,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3032,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3604,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11919,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6843,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10840,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9542,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10164,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4435,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5097,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4656,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2420,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12697,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3981,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2504,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (773,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (440,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2868,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9976,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1645,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14994,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3949,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7237,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6821,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12010,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7838,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13339,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4119,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13860,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9813,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (730,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6828,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1732,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7023,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8129,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7083,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14576,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8601,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14878,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11038,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14615,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3403,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9715,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13584,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14344,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11778,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13987,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3497,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6136,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1716,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11227,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1968,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9160,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11477,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10578,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7374,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13220,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7806,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1687,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7213,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8778,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4966,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11701,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4775,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8086,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4603,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3205,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2043,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14693,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11041,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5945,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2512,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6717,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10880,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2506,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7867,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14226,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13781,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4499,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10394,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4630,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10851,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10877,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14660,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8053,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9923,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11933,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5002,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1021,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3065,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1929,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3126,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14098,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (590,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (864,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14163,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1825,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9751,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7182,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6459,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4184,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13146,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2955,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3489,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14842,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8818,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6262,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3149,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6072,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5977,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13390,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (391,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11526,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12209,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7652,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12380,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6128,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14054,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (937,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7354,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9952,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1107,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13508,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12704,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12960,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9139,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1155,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12380,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10007,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2644,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13631,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5319,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3490,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13330,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10974,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13440,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14030,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11519,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12829,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11670,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10552,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2383,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9673,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3609,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11218,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2003,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13533,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3801,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8014,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5451,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10382,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5761,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6171,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11159,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6711,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10956,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10108,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1374,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1265,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1027,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5550,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6939,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13421,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12791,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4003,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3427,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6782,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4452,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14599,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4491,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10924,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2905,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5001,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7877,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13590,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (328,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11107,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14963,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10503,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5569,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (376,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6128,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6844,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14084,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7736,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4140,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11635,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6676,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7925,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3730,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11794,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4162,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5280,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11384,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1697,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9706,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5165,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14118,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5437,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2854,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14953,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13719,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14498,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5607,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3395,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8149,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13841,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3441,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13819,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1346,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7961,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1573,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9598,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14173,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1901,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14330,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13981,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6672,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2303,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1457,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7096,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10833,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5649,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14319,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1817,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14260,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (342,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14996,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11769,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4181,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (387,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1131,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2322,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1459,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4629,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7085,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3025,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8656,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5241,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12751,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9146,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14160,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8268,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3072,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10023,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8120,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11459,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6171,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12276,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6156,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8954,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8153,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11210,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2952,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (595,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6672,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9610,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8723,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3155,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12011,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12465,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12560,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8077,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1484,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6096,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2513,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11237,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11384,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13870,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6008,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5607,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1750,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6422,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13887,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13458,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (105,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11214,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3744,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12145,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3946,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14415,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2553,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4976,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4820,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8658,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7243,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5094,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3912,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11702,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10196,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11659,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4156,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8577,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9328,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11467,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5416,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9304,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3261,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4471,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2049,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12188,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10072,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8624,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1330,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12571,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9953,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11373,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4973,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10841,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2228,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11918,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2061,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11402,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6824,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6244,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3188,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8739,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13209,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14347,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6300,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12612,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1547,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7218,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14382,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10853,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6565,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (948,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3934,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13894,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2709,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3981,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14667,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4113,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5675,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14720,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6756,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6137,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14221,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4502,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1663,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12546,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10687,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10426,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8096,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3426,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5021,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8509,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8429,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8209,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3089,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9950,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7113,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5514,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (131,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3032,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14002,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12665,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4753,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3948,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (596,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12369,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13435,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14209,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12835,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1156,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11763,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (878,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10107,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1432,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6975,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6113,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3178,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6119,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10942,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9417,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9463,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7956,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8385,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7788,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11859,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11023,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14976,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11824,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7655,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6270,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13419,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4094,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9517,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5456,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3876,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9725,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (453,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14490,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12866,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10644,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12995,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13929,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4463,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13294,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8975,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12461,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7408,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1079,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8990,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11316,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10959,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11112,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1558,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7541,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12017,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11455,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6365,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5070,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2036,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3039,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2990,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3833,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (877,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (281,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8507,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7707,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2444,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (803,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11193,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9900,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9820,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (983,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3157,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9194,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4543,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3441,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8526,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9888,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10741,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4017,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1487,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (804,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1319,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4048,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10998,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10380,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5819,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13717,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12328,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11853,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4939,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10131,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (884,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5461,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (421,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4023,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6301,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4223,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14443,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4300,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9091,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7436,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2418,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3835,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14586,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1928,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7357,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4714,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8585,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (532,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13512,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6504,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8651,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3746,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10077,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3245,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5049,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11783,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1342,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9112,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1087,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1641,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3227,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8852,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6388,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10513,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14289,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12603,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14252,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7860,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1452,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14179,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14109,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7211,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11297,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12151,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6292,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7982,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1966,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8579,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4125,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8420,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1063,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9500,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12964,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9726,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2642,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8062,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6254,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8832,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3579,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12917,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11977,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12106,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4832,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12368,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11648,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5149,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2473,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11961,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3541,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13243,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12562,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9740,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (124,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5035,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10948,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1253,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3077,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9147,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8802,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6762,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5092,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6318,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11710,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4577,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2849,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5483,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7956,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13265,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (509,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9709,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4788,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13245,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4454,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4336,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14929,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14229,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7218,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5445,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13109,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12880,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3325,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14383,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6286,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11095,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13507,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5519,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13644,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14516,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4122,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14398,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2412,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10373,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5389,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5001,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (740,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11997,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11722,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (631,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13038,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6062,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2856,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1405,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10659,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7832,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (299,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3721,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11852,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2211,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3924,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2226,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6020,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10677,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8964,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13949,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5337,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12097,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4615,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4060,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9433,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13285,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12629,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10634,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4515,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9787,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10565,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11294,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12779,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6055,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10742,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1666,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7492,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10898,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4588,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9487,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (158,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2698,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11207,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5508,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8929,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6452,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2697,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7128,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (225,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7414,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5053,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4564,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4618,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14792,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9672,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6232,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5924,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (805,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10536,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5219,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3777,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14110,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10326,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8360,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2447,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7322,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4377,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11863,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14343,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9927,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3616,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11650,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8222,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11699,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10662,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13001,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13236,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6899,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12884,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2301,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13395,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9216,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10191,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10559,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4181,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7247,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2216,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14596,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13159,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (752,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9551,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13524,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10697,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6877,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12500,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4740,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7862,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12545,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13945,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6194,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9865,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10339,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8077,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11916,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10567,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3781,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10889,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4204,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9779,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (782,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14242,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11623,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11046,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8668,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8987,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2958,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14737,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3498,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13243,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12045,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1599,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10613,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11209,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4415,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10854,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8152,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3621,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4076,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4444,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14000,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7805,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3803,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3875,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6209,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8298,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6289,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8994,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1275,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10411,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10137,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13040,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3665,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14710,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8921,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7583,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2660,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (435,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14482,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9454,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1349,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8307,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4984,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8917,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14951,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9888,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4763,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8995,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13000,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (176,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14942,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10449,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2188,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14657,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4474,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10622,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1354,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14548,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9639,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (545,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11533,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8146,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6947,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6765,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7066,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4587,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14977,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2835,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2961,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10968,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13618,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6582,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6902,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4985,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6119,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10215,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14401,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9965,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13412,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (460,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7596,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12915,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7517,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4526,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8490,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12763,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9143,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12228,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5555,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14231,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4386,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2083,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8623,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7987,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7773,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10207,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5741,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6122,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10584,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5864,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2847,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5723,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14783,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3550,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1338,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5622,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4759,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9243,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6508,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3659,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3957,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3439,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7713,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1684,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10971,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6169,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5505,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4017,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9106,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10294,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9343,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (315,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12431,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6766,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2121,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4532,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1365,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7535,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (603,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8314,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2491,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13350,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13543,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (426,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9687,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11208,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8795,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12050,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10617,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2605,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13971,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6176,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (219,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10830,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7717,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9878,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2277,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6367,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9951,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3707,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1193,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7714,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (335,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5680,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7500,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9640,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9618,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8842,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1532,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8008,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5814,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5260,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6782,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1961,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12191,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (673,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13359,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5944,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12435,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2610,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11221,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4975,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3234,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11258,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12413,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7907,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2966,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9836,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9971,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6905,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4716,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11149,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12381,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12598,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11426,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13501,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11267,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11576,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2760,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8106,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7879,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2397,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4805,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4493,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11923,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5797,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14400,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7929,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13311,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5500,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (824,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6287,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11331,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9779,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7876,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14967,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13300,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6000,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8441,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1750,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12611,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7094,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1952,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5344,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6882,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12929,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1464,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14995,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4859,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5765,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13295,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11009,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1976,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2503,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6732,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1308,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3729,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (226,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1129,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10364,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7160,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (123,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13322,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7547,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3059,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14238,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4014,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14223,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8750,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7670,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1577,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9126,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4126,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9524,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14603,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7077,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9841,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12025,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9463,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14173,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4054,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8471,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (413,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5842,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14489,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6586,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1723,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9305,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10286,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3618,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1478,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (602,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2863,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8310,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3485,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3745,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9135,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5512,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (201,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12274,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11804,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11085,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12633,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14867,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6439,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13520,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3726,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1917,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9249,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5260,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13167,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11209,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3366,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9645,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10458,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3728,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10810,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9149,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11375,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12600,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5543,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3466,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1671,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5688,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14610,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7532,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7990,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8753,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6156,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (758,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9749,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2855,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4863,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6237,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12436,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9793,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10739,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8650,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12816,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8778,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3190,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3410,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5194,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13257,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (555,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9826,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14346,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8585,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12418,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11987,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6549,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6314,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1781,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6065,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11228,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12214,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4247,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10445,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (497,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7329,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4652,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2350,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2790,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10569,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9517,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13978,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9915,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9523,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10935,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3224,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (502,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7288,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10080,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4176,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2683,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6912,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3032,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7454,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7999,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14086,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7345,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10501,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9045,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5368,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3108,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10154,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10541,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13573,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (924,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6624,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13850,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1072,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8540,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11777,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6371,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13805,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4051,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1707,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (514,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10840,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2196,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11742,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4859,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14752,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12674,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9012,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14537,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13944,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11859,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8045,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12214,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (8055,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11133,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9765,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9465,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1721,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7571,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3764,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (6453,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13948,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (5776,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13969,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14534,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7606,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13156,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4259,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11449,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2755,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3745,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4940,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (7085,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10991,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11330,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3726,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11591,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9224,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3503,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (14174,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2735,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (3147,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (680,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9444,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10244,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11567,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (1173,'Pocitac ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (561,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4543,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2412,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (13359,' DVD');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4953,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9358,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2212,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (11899,' Pamet ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (4003,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (595,' Playstation ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (9460,' Disk ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (12094,' Televize ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10322,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (2606,' Monitor ');
INSERT INTO Zbozi (Cena,Nazev) VALUES (10337,' Monitor ');
